./testclient2.py foo xxx nana "Testtext2 mu mu more text"
./testclient2.py xx nana y "Testtext3 snsnsns mu mu more text"
./testclient2.py xx nana y "Testtext4 snsnsns mu mu more text"
./testclient2.py foo bar xxx yyy "Snattrafattra"
./testclient2.py foo bar xxx yyy "Mumumimi"
./testclient2.py foo bar xxx yyy "Mumumimi"
./testclient2.py foo bar xxx yyy "Snattrafattra"
./testclient2.py xx nana y "Testtext4 snsnsns mu mu more text"
./testclient2.py xx nana y "Testtext3 snsnsns mu mu more text"
./testclient2.py foo xxx nana "Testtext2 mu mu more text"
